name: text_mass_
tag: "v1"
exp_root_dir: "outputs"
seed: 0

data_cls: tpa.data.msrvtt.MSRVTTDataModule
data: 
  videos_dir: "/data1/zhipeng/dataset_video/MSRVTT/videos/all/"
  db_file: "data/MSRVTT/MSRVTT_data.json"
  train_file: "9k"
  train_csv: "data/MSRVTT/MSRVTT_train.9k.csv"
  test_csv: "data/MSRVTT/MSRVTT_JSFUSION_test.csv"
  input_res:  224

system_cls: tpa.systems.textmass_tpa.TextMassTPA
system:
  loss:
    lambda_support_set: 0.0
  tokenizer_cls: tpa.models.tokenizers.clip_tokenizer.CLIPTOKENIZER
  tokenize:
    clip_arch: 'openai/clip-vit-base-patch32'

  backbone_cls: tpa.models.transformers.clip_stochastic.CLIPStochastic
  backbone:
    clip_arch: 'ViT-B/32'
    num_frames:  12
    embed_dim:  512
    num_mha_heads:  1
    transformer_dropout: float = 0.3
    stochastic_prior: 'uniform01'
    stochastic_prior_std: 1.0        
    input_res: 224

  # post_processor_cls:
  # pool_type:
  save_memory_mode: False
  stochasic_trials: 20
  DSL: False
  metrics:  tpa.utils.metrics.t2v_metrics

trainer:
  max_epochs: 5
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  check_val_every_n_epoch: 1
  enable_progress_bar: true
  # precision: bf16-mixed
  # gradient_clip_val: 1.0


checkpoints:
  every_n_epochs: 1 # never saved
